FROM ubuntu

WORKDIR /app
COPY . ./

RUN apt update && apt install curl -y && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt install -y nodejs && cd resources && chmod +x ./aapt2 && apt install default-jdk -y && cd .. && npm i 

EXPOSE 80

CMD ["npm","start"]