FROM ubuntu

WORKDIR /app
COPY . ./

RUN apt update && apt install curl -y && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt install -y nodejs && npm i 

EXPOSE 1337

CMD ["npm","start"]